### ISSUE TITLE
Empty <binding_name>.cpp generated

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#151]
I'm using master branch of Chimera to generate bindings for `dartpy` (branch: [updating_for_dart_6.1](https://github.com/personalrobotics/dartpy/tree/updating_for_dart-6.1)). Chimera currently always generates an empty `dartpy.cpp` without any warning or error, which I believe it's a bug. `dartpy.cpp` should contain something like:
```cpp
#include <boost/python.hpp>

BOOST_PYTHON_MODULE(dartpy)
{
::boost::python::docstring_options options(true, true, false);

//  ...

}
```

Not surprisingly, the empty `dartpy.cpp` results in failure of `import dartpy` as
```shell
>>> import dartpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initdartpy)
```
If I add the following code into `dartpy.cpp` manually, `dartpy` is imported but nothing binded:
```cpp
#include <boost/python.hpp>

BOOST_PYTHON_MODULE(dartpy)
{
::boost::python::docstring_options options(true, true, false);
}
```

**Comment by jslee02** [comment]
If someone works on this, please use [dartpy_friendly_version] branch of DART to workaround #148 .

**Comment by psigen** [comment]
Got it, thanks for the note

**Comment by psigen** [comment]
I think this issue is actually a very unituitive error in parsing the `chimera.yml` (see #160).  Removing the `module` configuration section from that file allows chimera to drop back to the default python bindings, which seems to repopulate `dartpy.cpp` correctly.

Short term, I'll help open a branch of `dartpy` with the correct syntax for `chimera.yml`.  Longer term we need to patch chimera to report this error immediately rather than silently converting it into an empty template.  I have opened #160 to track that, so I'll close this issue here.

**Comment by jslee02** [comment]
Thanks for the investigating on this issue!

To clarify, how the `module` configuration section was incorrect? Was it a wrong path or a missing `!file` tag?
